export const SET_POSTS = 'SET_POSTS'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const GET_SINGLE_POST = 'GET_SINGLE_POST'
export const GET_POSTS_BY_USER = 'GET_POSTS_BY_USER'
export const TOGGLE_LIST = 'TOGGLE_LIST'
