version: '3'

services:
  backend:
    image: top-v20-backend
    build: .
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - 8080:8080
    command: npm run dev
    volumes:
      # mount current dir into docker container
      - .:/app
      # igonre local node_modules, use container node_modules
      - /app/node_modules

  db:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ~/data:/data/db
